version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: mkdir -p dist
      - run: ls
      - persist_to_workspace:
          root: ~/dist
          paths:
            - dist
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run build
          command: npm run build
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - attach_workspace:
          at: ~/data
      - checkout
      - run:
          name: Upload to s3
          command: ./ops/deploy.sh
workflows:
  react-build:
    jobs:
      - build
      - deploy:
          requires:
            - build
